# Site settings
title: alekseydurachenko.github.io
email: durachenko.aleksey@gmail.com
description: >
  Персональный блог
baseurl: ""
url: "https://alekseydurachenko.github.io"
github_username: alekseydurachenko.github.io

# Build settings
markdown: kramdown

timezone:    Aisa/Novosibirsk
